version: '3'
services:
  dev:
    command: python3 /root/app/app.py   
    image: a1st124481:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./app:/root/app 
      - ./code:/root/code 
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80